version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PATH=${DB_PATH}
    volumes:
      - ./db:/usr/src/app/db
    user: "node"

volumes:
  db: