services:
  app:
    build:
      context: .
      target: production
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PATH=${DB_PATH}
      - PORT=${PORT}
      - TYPEORM_SYNC=${TYPEORM_SYNC}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./db:/usr/src/app/db
    user: "node"

volumes:
  db: